# Main config
owner: regiocloud
repo: status
sites:
  - name: REGIO.digital
    url: https://regio.digital

status-website:
  cname: status.regio.digital
  logoUrl: https://raw.githubusercontent.com/osism/openstack-themes/main/horizon/regiocloud/static/img/logo-splash.svg
  favicon: https://raw.githubusercontent.com/osism/openstack-themes/main/horizon/regiocloud/static/img/favicon.ico
  faviconSvg: https://raw.githubusercontent.com/osism/openstack-themes/main/horizon/regiocloud/static/img/favicon.ico
  name: REGIO.status
  theme: dark
  introTitle: "**REGIO.status** displays the status of all our services that are relevant for customers."
  introMessage: If a service is down or we are planning maintenance, it will be indicated on this page. So if a service is not responding, you can see here if there is an outage or if maintenance is currently being performed.
  navbar:
    - title: REGIO.digital
      href: https://regio.digital

i18n:
  footer: This page is powered by [REGIO.digital](https://regio.digital)
